server:
  port: 8668
dubbo:
  application:
    name: sjmt-oss-center
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://106.54.177.184:8848
    username: nacos
    password: nacos
    parameters.register-consumer-url: true